export {default as Login} from'./Login'
export {default as Navbar} from './Navbar'
export {default as Signin} from './Signin'
export {default as Vedicmaterials} from './Vedicmaterials'
export {default as Vedicpractitioner} from './Vedicpractitioner'
export {default as Patientfeedback} from './Patientfeedback'
export {default as About} from './About'
export {default as Home} from './Home'
export {default as Admin} from './Admin'

